### ISSUE TITLE
After the Rain - Missing

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#104]
Seems the TVDB ID isn't in the file. I'm showing:

```
  <anime anidbid="12906" tvdbid="" defaulttvdbseason="" episodeoffset="" tmdbid="" imdbid="">
    <name>Koi wa Ameagari no You ni</name>
  </anime>
```

English:  After the Rain
Japanese:  Koi wa Ameagari no You ni

AniDB:  12906
TBDB:  6496727

**Comment by sixtenbe** [comment]
Fixed in latest [commit](https://github.com/ScudLee/anime-lists/commit/ce24e81bf6465e9e38192408f3ba28e205c4af37)
