### ISSUE TITLE
Missing: Wotakoi: Love Is Hard for Otaku

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#120]
Show:  
AniDB:  [13293](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=13293)
TheTVDB:  [341425](https://www.thetvdb.com/?tab=series&id=341425&lid=7)

```
<anime anidbid="13293" tvdbid="341425" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Wotakoi: Love Is Hard for Otaku</name>
  </anime>
```

**Comment by sixtenbe** [comment]
This is already added in a previous [commit](https://github.com/ScudLee/anime-lists/commit/e68c4ae1a6d4554f1043d9a58bfafb26a7889fbc)

**Comment by sven-7** [comment]
Thanks. Couldn't find it for some reason. 

Closing #120.
