### ISSUE TITLE
Zettai Muteki Raijin Ou anidbid 4486 with wrong tvdbid

### ISSUE THREAD

**Issue by KurtzPT** [ScudLee/anime-lists#123]
The correct tag below.

```
  <anime anidbid="4486" tvdbid="265264" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Zettai Muteki Raijin Ou</name>
  </anime>
```

**Comment by sixtenbe** [comment]
The current mapping to tvdbid-[193911](https://www.thetvdb.com/series/matchless-raijin-oh) is correct from what I can see.

The official English title of Zettai Muteki Raijin Ou is: "Matchless Raijin-Oh" and the tvdid you suggested lacks artwork and much of the data. To me it looks like somebody didn't know that TVDB doesn't really do unofficial transcriptions for the titles like AniDB does and added an entry with the unofficial transcription used by AniDB.

**Comment by KurtzPT** [comment]
You are right, my first search was using the full original title which it gave me only one match 265264

Using just Raijin Ou on the search gives me two results: 265264 and 193911. 

Since mine is mostly incomplete I'll close my issue.
