### ISSUE TITLE
Missing - HANEBADO!

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#127]
Show:  HANEBADO!
AniDB:  [13783](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=13783)
TheTVBD:  [348294](https://www.thetvdb.com/series/hanebado)

```
<anime anidbid="13783" tvdbid="348294" defaulttvdbseason="1">
  <name>HANEBADO!</name>
</anime>
```

**Comment by sixtenbe** [comment]
Now added, sry for the delay
