### ISSUE TITLE
Overlord 2 & 3 missing specials mapping

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#130]
https://www.thetvdb.com/series/overlord/seasons/0
########################################
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=12952
(AniDB) S1 | Pleiades 2 - 1 = (TVDB) 14 | Pure Pure Pleiades 2 - Play 1: The Dawn of Confusion
########################################
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=14008
(AniDB) S1 | Pleiades 3 - 1 = (TVDB) 27 | Pure Pure Pleiades 3 - Play 1: A Ruler’s New Melancholy

**Comment by sixtenbe** [comment]
Only covers up to Pleades 4 on Overlord 3 for now so remind me by opening a new issue when needed.
