### ISSUE TITLE
"Grappler Baki: Saidai Tournament Hen" special mapping missing

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#133]
Hi,
S0E1 special mapping missing

Grappler Baki: Saidai Tournament Hen - http://anidb.net/perl-bin/animedb.pl?show=anime&aid=880
SP1 | Rencounter

Baki the Grappler - https://www.thetvdb.com/series/baki-the-grappler/seasons/all
https://www.thetvdb.com/series/baki-the-grappler/episodes/647821
S2 E24 | Rencounter

```xml
  <anime anidbid="880" tvdbid="79237" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
    <name>Grappler Baki: Saidai Tournament Hen</name>
  </anime>
```

**Comment by EndOfLine369** [comment]
Shouldn't this have been `anidbseason="0"` ?
What was entered:
```xml
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="2">;1-24;</mapping>
    </mapping-list>
```

**Comment by sixtenbe** [comment]
oops you're right, changed it.

**Comment by EndOfLine369** [comment]
Thanks 😄
