### ISSUE TITLE
Overlord 3 Specials mapping

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#147]
Please fix the rest of the mapping for Pleades 4 on Overlord 3 (re: https://github.com/ScudLee/anime-lists/issues/130)

https://www.thetvdb.com/series/overlord/seasons/0
########################################
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=14008
(AniDB) S1 | Pleiades 3 - 1 = (TVDB) 27 | Pure Pure Pleiades 3 - Play 1: A Ruler’s New Melancholy

**Comment by ScudLee** [comment]
Should be fixed in f4f26bf60100fdc4638cfb7dcebe3466795b0ff0

Thanks!
