### ISSUE TITLE
"Toaru Majutsu no Index" specials mapping

### ISSUE THREAD

**Issue by atraholt** [ScudLee/anime-lists#149]
Each season of this show has one or more "Index-tan" specials that are currently not being mapped correctly.
https://www.thetvdb.com/series/a-certain-magical-index/seasons/0
s0e1 = 5975 S1
s0e2 = 5975 S2
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=5975
s0e3 = 7599 S1
s0e4 = 7599 S2
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=7599

s0e5 and s0e6 are being mapped correctly to the movies.

**Comment by ScudLee** [comment]
Should be fixed in ebd291fe26892e2e02fb269886e666910af97300

Thanks!
