### ISSUE TITLE
"Mushi-shi" specials corrections due to TVDB shuffling

### ISSUE THREAD

**Issue by atraholt** [ScudLee/anime-lists#152]
TVDB seems to have shuffled episode 11 (double duration episode that aired back-to-back) of Mushishi Zoku Shou from s0e3 to now be s0e4 and s0e5.
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10384
https://www.thetvdb.com/series/mushi-shi/seasons/0

This also means that Mushishi Zoku Shou (2014): Suzu no Shizuku also needs to be shifted up an episode to s0e6. It's currently mapped as s0e5.
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10991

This is further complicated by that S2 and S3 of Mushishi Zoku Shou (2014) are not in TVDB, but S1 is, as s0e7.
https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10571

**Comment by ScudLee** [comment]
Should all be fixed in 447c76126a5d752b07dbbb91b4bf2e53a52c3d23

Thanks!
