### ISSUE TITLE
Fafner-Heaven and Earth wrong mapping

### ISSUE THREAD

**Issue by Feredzhanov** [ScudLee/anime-lists#159]
The mapping should be:
`  <anime anidbid="7304" tvdbid="81110" defaulttvdbseason="0" episodeoffset="" tmdbid="137502" imdbid="">
    <name>Soukyuu no Fafner: Dead Aggressor - Heaven and Earth</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-4;</mapping>
    </mapping-list>
  </anime>`
![image](https://user-images.githubusercontent.com/27891431/50406668-873d1f80-07d1-11e9-9c85-c13cfb21774c.png)

**Comment by ZeroQI** [comment]
Adding specials 1 and 2 as tvdb special 3 and 4
```
  <anime anidbid="1806" tvdbid="81110" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-2;2-3;</mapping>
    </mapping-list>
    <name>Soukyuu no Fafner: Dead Aggressor</name>
    <supplemental-info>
      <studio>Xebec</studio>
    </supplemental-info>
  </anime>
```

Moving tvdb special 2 to 4:
```
<anime>
    <name>Soukyuu no Fafner: Dead Aggressor - Heaven and Earth</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-4;</mapping>
    </mapping-list>
  </anime>
```

No change, already special 1
 ```
 <anime anidbid="3323" tvdbid="81110" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Soukyuu no Fafner: Dead Aggressor - Right of Left</name>
    <supplemental-info>
      <studio>Xebec</studio>
    </supplemental-info>
  </anime>
```

Specials 3 and 4 are dvd specials, so TVDB will not include
https://www.thetvdb.com/series/fafner/episodes/1817581

**Comment by sixtenbe** [comment]
should be good now
