### ISSUE TITLE
DAYS Specials

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#173]
The specials for DAYS have been added to [TVDB as S0E3-E5](https://www.thetvdb.com/series/days/seasons/0).  [They are on AniDB here](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=12621) as 12621.

Current entries:

```
  <anime anidbid="12621" tvdbid="311149" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
    <name>Days: Touin Gakuen Ikusa!</name>
  </anime>
```

```
  <anime anidbid="11875" tvdbid="311149" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Days</name>
  </anime>
```

**Comment by sixtenbe** [comment]
fixed in [dfc2efa](https://github.com/ScudLee/anime-lists/commit/dfc2efad75d18ac7af3033e8eb8db0f23bfae8f1)
