### ISSUE TITLE
Cat Ninden Teyandee/Samurai Pizza Cats mapping update

### ISSUE THREAD

**Issue by yauncle** [ScudLee/anime-lists#253]
It seems someone has added the 2 recap episodes for "Cat Ninden Teyandee" to TheTVDB.
Recap 1, which is AniDB episode 10, is now on TVDB as episode 53.
Recap 2, ep 51 at AniDB, is TVDB ep 54.
If I understand correctly, this means:
`<mapping anidbseason="1" tvdbseason="1">;1-1;2-2;3-3;4-4;5-5;6-6;7-7;8-8;9-9;10-0;11-10;12-11;13-12;14-13;15-14;16-15;17-16;18-17;19-18;20-19;21-20;22-21;23-22;24-23;25-24;26-25;27-26;28-27;29-28;30-29;31-30;32-31;33-32;34-33;35-34;36-35;37-36;38-37;39-38;40-39;41-40;42-41;43-42;44-43;45-44;46-45;47-46;48-47;49-48;50-49;51-0;52-50;53-51;54-52</mapping>`
should become
`<mapping anidbseason="1" tvdbseason="1">;1-1;2-2;3-3;4-4;5-5;6-6;7-7;8-8;9-9;10-53;11-10;12-11;13-12;14-13;15-14;16-15;17-16;18-17;19-18;20-19;21-20;22-21;23-22;24-23;25-24;26-25;27-26;28-27;29-28;30-29;31-30;32-31;33-32;34-33;35-34;36-35;37-36;38-37;39-38;40-39;41-40;42-41;43-42;44-43;45-44;46-45;47-46;48-47;49-48;50-49;51-54;52-50;53-51;54-52</mapping>`
Or in other words, 10-0 -> 10-53 and 51-0 -> 51-54.

**Comment by purposelycryptic** [comment]
It seems this edit has since been reversed ¯\_(ツ)_/¯

On the positive side, it appears the "movie" has been added to the specials.

**Comment by sixtenbe** [comment]
Since issue is resolved by tvdb reverting to previous state I'm closing this.
