### ISSUE TITLE
Mobile Suit Gundam - The Origin

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#265]
This changed on TVDB.  This AniDB entry is now season 0. Not sure if I correctly formatted the entries below...

```
  <anime anidbid="8517" tvdbid="142601" defaulttvdbseason="0" episodeoffset="">
    <name>Kidou Senshi Gundam: The Origin</name>
  </anime>
```

[The new series](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=14496), will be season 1, AniDB 14496 and TVDB 142601.

```
  <anime anidbid="14496" tvdbid="142601" defaulttvdbseason="1" episodeoffset="">
    <name>Kidou Senshi Gundam: The Origin - Zen`ya Akai Suisei</name>
  </anime>
```

**Comment by sixtenbe** [comment]
Kidou Senshi Gundam: The Origin now has it's own entry [364883](https://www.thetvdb.com/series/gundam-the-origin-ova) and appears to have been purged from tvdbid 142601 and I can't seem to find where the new tv edit anidbid="14496" should go on tvdb, I can't call this resolved, nor can I fully resolve it myself at the moment.

**Comment by purposelycryptic** [comment]
Wow - that is new; TVDB ID 142601 was still there just days ago when I was double-checking issue-related edits. I'll have to see if there is something about it on the forums. [Kidou Senshi Gundam: The Origin - Zen`ya Akai Suisei](https://anidb.net/a14496) is literally just [Kidou Senshi Gundam: The Origin](https://anidb.net/a8517) re-cut for TV, so it's entirely possible someone made the case that it was a dupe, and it ended up wiped.

Currently, there isn't a single Gundam series on TheTVDB listed as 'airing', with the latest series shown ending in September 2018, so it is definitely gone, whatever the reason; it is certainly odd though, as, by TVDB rules, whenever a duplicate is purged, the one with the lower ID number remains - yet here we have 142601 getting purged in favor of 364883...

**Comment by purposelycryptic** [comment]
The [latest](https://forums.thetvdb.com/viewtopic.php?f=18&t=54236) I could find on the forums was from when it was mod-edited to the state it was in a few days ago, before the purge... And it isn't on the purge list either. This just keeps getting weirder.

**Comment by sixtenbe** [comment]
I believe it's a wait and see for the tv edit, but for the time being I've mapped the Origin OVA to the new tvdbid.

**Comment by purposelycryptic** [comment]
...and - [it's back](https://www.thetvdb.com/series/mobile-suit-gundam-the-origin)!

```xml
  <anime anidbid="14496" tvdbid="319976" defaulttvdbseason="1" episodeoffset="">
    <name>Kidou Senshi Gundam: The Origin - Zen`ya Akai Suisei</name>
  </anime>
```

No clue why, but it's the same entry as before, just with a different ID. We must have caught the DB in the middle of an update or something, the latest change is marked as 07/13/2019 5:15pm

**Comment by purposelycryptic** [comment]
I just ended up confusing myself by taking the TVDBID from the original post, rather than from the anime-list-master.xml, and forgot that it had changed, even though I think I was the one that made the edit  :oops:

**Comment by sixtenbe** [comment]
Since the entry reappeared I've added The OVA to the same tvdbid as the tv edit and this should now be fully resolved. [efb3b48](https://github.com/ScudLee/anime-lists/commit/efb3b48f2a683ebeed16a80e1d78cf2ab00bd4fa)

Reopen or make a new issue if it they change it again.

**Comment by purposelycryptic** [comment]
That seems like the best choice.
