### ISSUE TITLE
Magi - Sinbad incorrectly mapped

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#289]
Looks like Magi - Adventures of Sinbad is mapped to the regular version of Magi, not it's own TVDB entry. Correct should be:

```
 <anime anidbid="11672" tvdbid="310718" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Magi: Sindbad no Bouken (2016)</name>
  </anime>
```

and...

```
 <anime anidbid="10392" tvdbid="310718" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Magi: Sindbad no Bouken</name>
  </anime>
```

**Comment by purposelycryptic** [comment]
Looks like TheTVDB decided to give it its own entry at some point - its position as Magi S3 always was fairly awkward.

**Comment by sven-7** [comment]
It should definitely be it’s own entry, so I think that’s correct. It’s had one for a long time. I think they just deleted whatever extras they had.

**Comment by sixtenbe** [comment]
Fixed in commit [#8e5ffa](https://github.com/ScudLee/anime-lists/commit/88e5ffab49e452cdeb4590c9839eb7204253b508)
