### ISSUE TITLE
 Sword Art Online Alicization (Anidb ID 13493) S1 and S2 not mapped

### ISSUE THREAD

**Issue by ZeroQI** [ScudLee/anime-lists#300]
Sword Art Online Alicization [anidb-13493] have 2 specials not mapped propertly:
- S00E01 'Recollection' is mapped to TheTVDB ID 259640 'Sword Art Online' s00e01 'Sword Art Offline 1' instead of s00e24 'Alicization 18.5: Recollection'
- S00E02 'Reflection' is mapped to TheTVDB ID 259640 'Sword Art Online' s00e02 'Sword Art Offline 2' instead of s00e25 'Alicization 24.5: Reflection'

Currently:
```
  <anime anidbid="13493" tvdbid="259640" defaulttvdbseason="3" episodeoffset="" tmdbid="" imdbid="">
    <name>Sword Art Online: Alicization</name>
  </anime>
```

It should however be specials 1 and 2 under AniDB mapped to special 24 and 25 under TheTVDB:
```
  <anime anidbid="13493" tvdbid="259640" defaulttvdbseason="3" episodeoffset="" tmdbid="" imdbid="">
    <name>Sword Art Online: Alicization</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-24;2-25;</mapping>
    </mapping-list>
  </anime>
```

**Comment by sixtenbe** [comment]
Should be fixed now.
