### ISSUE TITLE
Add mapping for deadly sins special episode prisoners of the sky

### ISSUE THREAD

**Issue by StudioEtrange** [ScudLee/anime-lists#302]
I think this special episode should be mapped like that

_The deadly sins S00E09 "prisoners of the sky"_ ([link](https://www.thetvdb.com/series/the-seven-deadly-sins/episodes/6937368)) TVDBID : 284131

_The Seven Deadly Sins the Movie: Prisoners of the Sky_ ([link](https://anidb.net/anime/13286 )) ANIDBID:13286

I am not certain of the syntax :
```
<anime anidbid="13286" tvdbid="284131" defaulttvdbseason="1">
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-9;</mapping>
    </mapping-list>
  </anime>
```

**Comment by purposelycryptic** [comment]
Thanks for the update - TheTVDB has kind of gone through a second big bang, and everything is kind of crazy right now.

I have family visiting for the week, but if no one else has addressed this by then, I'll make the fix in my next Pull Request.

I'm not the owner or a collaborator for the Repo, just have a vested interest in keeping it up-to-date, and thought you should get an actual response to your issue (however late it may be at this point ;-) )

**Comment by sven-7** [comment]
I think the current mapping is correct for S0 with an 8 episode offset. 

  <anime anidbid="13286" tvdbid="284131" defaulttvdbseason="0" episodeoffset="8" tmdbid="" imdbid="tt9089294">
    <name>Gekijouban Nanatsu no Taizai: Tenkuu no Torawarebito</name>
  </anime>

I think this can be closed. I will add tmdbid to it tho.
