### ISSUE TITLE
tvdbid 78916 s00e03 Gantz O

### ISSUE THREAD

**Issue by hergonoway** [ScudLee/anime-lists#316]
Hello, 

I can't map Gantz and Gantz O in collection with Hama :D

current : 
```
<anime anidbid="11778" tvdbid="movie" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="tt5923962">
    <name>Gantz O</name>
</anime>
```

should be s00e03 (+tmdbid = 396263)  : 
```
<anime anidbid="11778" tvdbid="78916" defaulttvdbseason="0" episodeoffset="2" tmdbid="396263" imdbid="tt5923962">
    <name>Gantz O</name>
</anime>
```

I've added also the tmdbid but I'm not sure if I should since there's already an imdbid because of : 
> tmdbid/imdbid - themoviedb.org/imdb.com id. Only used for one-off titles, unless there's definitely a themoviedb.org entry. Only one will be filled, with preference going to the imdb.com id, but the imdb.com entry must correspond exactly with AniDb.net. May be marked as "unknown" for movies (other types are inconsistent on usage).

sources:
TVDB : https://thetvdb.com/series/gantz/seasons/official/0
TMDB : https://www.themoviedb.org/movie/396263-gantz-o

**Comment by sven-7** [comment]
Will close when 266eb31 is committed.
