### ISSUE TITLE
AniDB 14238 s0e01 Mapping Issue

### ISSUE THREAD

**Issue by vyressi** [ScudLee/anime-lists#317]
Anidb14238 s0e01 ( Special 1, S1 ) is currently mapped to TheTVDB-353666 S4, this is incorrect.

It should be mapped to Intium Iter, TheTVDB-353666 S00E05 ( episode 7307050 )

Or Intium Iter, TheTVDB-133728

On the same note, Anidb S2 should be mapped to s00e06
Anidb S3 should be s00e07
Anidb S4 should be s00e08
and s5 should be S00e09

**Comment by sven-7** [comment]
Will close when d17d114 is committed.
