### ISSUE TITLE
Ascendance of a Bookworm OVA

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#320]
https://anidb.net/anime/15300

https://thetvdb.com/series/ascendance-of-a-bookworm (ID 366263)

https://thetvdb.com/series/ascendance-of-a-bookworm/seasons/official/0
---- S0E1 & S0E2

AniDB S1E1 -> S0E1 & S0E2
AniDB S0E401 -> S0E1
AniDB S0E402 -> S0E2

**Comment by sven-7** [comment]
This can be closed. Fixed in commit e8d6bae.
