### ISSUE TITLE
Asteroid in Love (Special)

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#321]
https://anidb.net/anime/14707
https://anidb.net/episode/226793
---- Episode: Koi Suru Asteroid - S1 - Sparkle`s Special Issue

https://thetvdb.com/series/koisuru-asteroid (ID 371444)
https://thetvdb.com/series/koisuru-asteroid/episodes/7581254
---- Recap: Sparkle's Special Issue

AniDB S0E1 -> TVDB S0E13

**Comment by sven-7** [comment]
This can be closed. Fixed in commit e8d6bae.
