### ISSUE TITLE
Otaku ni Koi wa Muzukashii: Youth

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#322]
https://anidb.net/anime/14405

https://thetvdb.com/series/341425 (ID 341425)
https://thetvdb.com/series/341425/episodes/6832022

AniDB S1E1 -> TVDB S0E1
```
  <anime anidbid="14405" tvdbid="341425" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Otaku ni Koi wa Muzukashii: Youth</name>
  </anime>
```

**Comment by sven-7** [comment]
This can be closed. Fixed in commit e8d6bae.
