### ISSUE TITLE
Mapping for Psycho-Pass First Inspector and Sinners of the System are not accurate

### ISSUE THREAD

**Issue by dekarguy** [ScudLee/anime-lists#330]
Sinners of a System - anidb 13894 should map to tvdb 262090 eps 13-15
First Inspector - anidb 15308 should map to tvdb 262090 eps 16-18

It looks like the mapping for First Inspector exists, but it maps to tvdb 0 instead of the correct entry

**Comment by sven-7** [comment]
This can be closed. Fixed in commit e8d6bae.
