### ISSUE TITLE
Heya Camp is on TVDB, can be removed from todo

### ISSUE THREAD

**Issue by dekarguy** [ScudLee/anime-lists#371]
should be updated to: 

```
  <anime anidbid="14439" tvdbid="330692" defaulttvdbseason="0" episodeoffset="4" tmdbid="" imdbid="">
    <name>Heya Camp</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-17;2-0;</mapping>
    </mapping-list>
  </anime>
```

I think it is right, don't really have a way of testing it

**Comment by reconman** [comment]
This repo is no longer being actively maintained and used.

Head over to https://github.com/Anime-Lists/anime-lists.

You probably need to update your ASS and Hama to make use of the new repo.
