### ISSUE TITLE
Fate/Zero and Fate/stay night UBW split, various minor findings

### ISSUE THREAD

**Issue by TheFireKahuna** [ScudLee/anime-lists#53]
Fate/Zero
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8160
 Fate/Zero (2012)
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8880
 Fate/Zero (TVDB)
http://thetvdb.com/?tab=season&seriesid=275798&seasonid=568956&lid=7

Fate/stay night: Unlimited Blade Works (2014)
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=9977
 Fate/stay night: Unlimited Blade Works (2015)
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=10760
 Fate/stay night: Unlimited Blade Works (TVDB)
http://thetvdb.com/?tab=season&seriesid=278626&seasonid=577004&lid=7

AniDB splits them up as aired, TVDB has them as one season. I think the mapping needs to be updated.

The only other major mapping issue I've found is that Ore Monogatari is missing tvdb data, despite the fact that it exists.
http://thetvdb.com/?tab=season&seriesid=289905&seasonid=607826&lid=7

The following are the only issues I found with various specials/ovas.
Infinite Stratos Special 1 (anidb) has no metadata from the TVDB, but I believe its there
http://thetvdb.com/?tab=season&seriesid=219131&seasonid=390011&lid=7

Toradora! Special 1 (True Meaning of Bento) needs to map to special 4 on the TVDB, not special 1
http://thetvdb.com/?tab=episode&seriesid=83277&seasonid=35763&id=4225416&lid=7

Lastly, Bakemonogatari seems to have the anidb specials order rearranged, from 2-4 being ep 13-14-15 to ep 1-3 being 13-14-15, the mapping might need to be updated too. 
http://thetvdb.com/?tab=season&seriesid=102261&seasonid=86961&lid=7

**Comment by ScudLee** [comment]
All fixed (I hope), except for the Fate episodes (per my [forum post](http://forum.kodi.tv/showthread.php?tid=142835&pid=2130082#pid2130082)).  Thanks!
