### ISSUE TITLE
Anime-List-Master (Corrections)

### ISSUE THREAD

**Issue by Dingmatt** [ScudLee/anime-lists#54]
If I'm understanding the mapping format correctly then the season number mapping in Black Lagoon should be 0 rather than 1.

`<anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
<name>Black Lagoon</name>
<mapping-list>
<mapping anidbseason="`**0**`" tvdbseason="0">;5-0;</mapping>
</mapping-list>
</anime>`

Regards,

Edit: See further corrections below

**Comment by Dingmatt** [comment]
Thought I'd add a few more corrections to:

`<anime anidbid="3395" tvdbid="79604" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Black Lagoon</name>
    <mapping-list>
      <mapping anidbseason="**0**" tvdbseason="0">;5-0;</mapping>
    </mapping-list>
  </anime>

  <anime anidbid="4597" tvdbid="79604" defaulttvdbseason="1" episodeoffset="12" tmdbid="" imdbid="">
    <name>Black Lagoon: The Second Barrage</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="**0**">;1-5;2-6;3-7;</mapping>
    </mapping-list>
  </anime>

  <anime anidbid="11148" tvdbid="**299326**" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Valkyrie Drive: Mermaid</name>
  </anime>
</anime-list>`

**Comment by ScudLee** [comment]
Fixed in a13640e84ed26c356a9133579eaede0e9fad4332.

Thanks! (Apologies for my slowness)
