### ISSUE TITLE
aid:10027, Space Dandy; mapping incorrect

### ISSUE THREAD

**Issue by Dingmatt** [ScudLee/anime-lists#60]
The mapping has an colon between entries 2 and 3 rather than the needed semicolon.

i.e. this
`<mapping anidbseason="0" tvdbseason="0">;1-0;2-1:3-2</mapping>`

needs changing to this
`<mapping anidbseason="0" tvdbseason="0">;1-0;2-1;3-2</mapping>`

**Comment by ScudLee** [comment]
Thank you for the correction.  I'm sorry it took me so long to respond.

I promise to be more responsive in the future (now that real life has settled down somewhat).
