### ISSUE TITLE
aid:11169 'Cyborg 009 vs. Devilman' tvdbid: 72745

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#62]
Cyborg 009 vs. Devilman is listed under Cyborg 009 (2001) as specials.

http://thetvdb.com/?tab=season&seriesid=72745&seasonid=20210&lid=7

**Comment by ScudLee** [comment]
Thank you for the correction.  I'm sorry it took me so long to respond.

I promise to be more responsive in the future (now that real life has settled down somewhat).

**Comment by sven-7** [comment]
Thanks!
