### ISSUE TITLE
aid:8624 'Gensou Mangekyou: The Memories of Phantasm' tvdbid:285209

### ISSUE THREAD

**Issue by EndOfLine369** [ScudLee/anime-lists#72]
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=8624

http://thetvdb.com/?tab=series&id=285209

**Comment by ScudLee** [comment]
Thank you for all the corrections!  I'm sorry it took me so long to respond.

I promise to be more responsive in the future (now that real life has settled down somewhat).
