### ISSUE TITLE
Fix for Another special

### ISSUE THREAD

**Issue by deusxanime** [ScudLee/anime-lists#82]
Tried posting to the forum thread but it has been a week without a peep, so figured I'd try posting here as well and see which gets noticed first. Here's copy-paste of most of what I put on that thread --

Just getting started going through my collection and ran into a missing mapping for "Another". AniDB #8556 special for this series is #2, but is s0e03 on the TheTVDB #254349 listings. So would need to add this line I believe to the Another entry in the xml, correct?:

\<mapping anidbseason="0" tvdbseason="0"\>;2-3;\</mapping\>

Not sure if would cause an issue/conflict though where the OVA series "Another: The Other - Inga" (AniDB #8625) is also mapped to TheTVDB #254349 Season 0. Currently only 1 episode in the OVA so it wouldn't displace s0e02.

**Comment by sixtenbe** [comment]
Should be correct now.
