### ISSUE TITLE
More fixes for anime list xml

### ISSUE THREAD

**Issue by deusxanime** [ScudLee/anime-lists#83]
Some more notes on issues I've found as I've started sorting and adding anime to Plex using ASS/HAMA made by ZeroQI.

- Sound! Euphonium season 1 specials missing mappings, needed due to OVA numbered different between anidb and tvdb
```
  <anime anidbid="10889" tvdbid="289884" defaulttvdbseason="1">
    <name>Hibike! Euphonium</name>
  </anime>
```
- Strike Witches operation victory arrow, should map to tvdb s0e03-e05 (NOT season 4)
```
  <anime anidbid="10198" tvdbid="82484" defaulttvdbseason="0">
    <name>Strike Witches: Operation Victory Arrow</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="4">;1-3;2-4;3-5;</mapping>
    </mapping-list>
  </anime>
```
- Strike Witches (original 2007 single episode ova) mapping to nothing, but should map to s0e01
```
  <anime anidbid="4530" tvdbid="82484" defaulttvdbseason="0">
    <name>Strike Witches</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-0;</mapping>
    </mapping-list>
  </anime>
```
- WWW.Working!! (www.wagnaria!!) tvdbid 316864 is wrong/changed, now should be 317802
```
  <anime anidbid="12059" tvdbid="316864" defaulttvdbseason="1">
    <name>Www.Working!!</name>
  </anime>
```
- No entry for "Koneko no Chii: Ponponra Daibouken" anidb 12103, should map to tvdb 81844 s3
- Flying Witch needs Special mappings due to special episode 5.5 numbered different between anidb and tvdb
```
  <anime anidbid="11469" tvdbid="300816" defaulttvdbseason="1">
    <name>Flying Witch</name>
  </anime>
```

**Comment by deusxanime** [comment]
- certain magical index movie, no mapping for special
```
  <anime anidbid="8694" tvdbid="83322" defaulttvdbseason="0" imdbid="unknown">
    <name>Gekijouban Toaru Majutsu no Index: Endymion no Kiseki</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-5;</mapping>
    </mapping-list>
```
- certain scientific railgun s ova, mapped to nothing, should go to s0e09
```
  <anime anidbid="10453" tvdbid="114921" defaulttvdbseason="0">
    <name>Toaru Kagaku no Railgun S: Daiji na Koto wa Zenbu Sentou ni Osowatta</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-0;</mapping>
    </mapping-list>
  </anime>
```

**Comment by sixtenbe** [comment]
The strike witched anidbid="4530" is correctly matched as far as I see. The thing being mapped to nothing is the anidb 8 min special and the main episode should still be mapped to tvdb s0e01

**Comment by deusxanime** [comment]
Yep you are right on a4523, I misread that one. I have many more fixes that I've been working on the past month. How often do you update it?

**Comment by sixtenbe** [comment]
I can't update this, which is why I forked this for my own needs.

Running https://github.com/sixtenbe/anime-lists/tree/updated_animeids as my main branch to get new animeids.

**Comment by deusxanime** [comment]
What are you working with/for? I'm working with ZeroQI from Plex forums. He has built a Plex scanner and agent (ASS & HAMA) and referred to ScudLee list to do mappings in his code, but we've decided, at least at this point, it is abandoned (until they respond to these updates/issues and fix things) and he has an ongoing "corrections" xml as part of his scanner.

https://github.com/ZeroQI/Absolute-Series-Scanner/blob/master/anime-list-corrections.xml

I'll be putting my fixes in there for the time being, as that is what I'm using. (He also has local file override as part of the scanner which is nice so I can drop in xml files also with my folders and get them working correctly in Plex)

**Comment by sixtenbe** [comment]
I'm using the hama agent and I'm just manually editing the ANIDB_TVDB_MAPPING variable in the script to point to my branch.

**Comment by sixtenbe** [comment]
Had a look at ZeroQI's correction and added the correct ones (some syntax errors in it and some just wrong or non edits). But it's still about 100 edits/additions behind my branch, to which I'll likely add anything aired by crynchyroll.

**Comment by deusxanime** [comment]
Yeah I still have to drop my updates into ZeroQI's correction xml, bit behind there. I'm also having to add new shows (at least the ones I'm grabbing), so will be adding those as well.

**Comment by sixtenbe** [comment]
I have probably already added those series to my branch so, might it not be an idea to ask ZeroQI to switch from the scudlee main to my fork, or does he want to stay in case scudlee return to once again maintain it?
