### ISSUE TITLE
Missing: WorldEnd: What do you do at the end of the world? Are you busy? Will you save us?

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#91]
I believe  "WorldEnd: What do you do at the end of the world? Are you busy? Will you save us?" is missing.  

Japanese Title:  Shuumatsu Nani Shitemasuka? Isogashii Desuka? Sukutte Moratte Ii Desuka?

Shortened:  SukaSuka

TVDB:  325208
AniDB:  12238

**Comment by sixtenbe** [comment]
Thanks, I missed adding that one.
