### ISSUE TITLE
Missing - King's Game

### ISSUE THREAD

**Issue by sven-7** [ScudLee/anime-lists#98]
I think this just aired today, so it may just not have been in the last update batch.

English:  King's Game The Animation
Japanese:  Ou-sama Game The Animation

TVDB ID:  [332981](https://www.thetvdb.com/?tab=series&id=332981&lid=7)
AniDB ID:  [13335](http://anidb.net/perl-bin/animedb.pl?show=anime&aid=13335)

**Comment by sixtenbe** [comment]
Appears I managed to miss this when going through the AniDB schedule for the week.
