### ISSUE TITLE
The Case File of Young Kindaichi Returns & The Case File of Young Kindaichi Returns (2015)

### ISSUE THREAD

**Issue by avluis** [ScudLee/anime-lists#99]
I'm still learning how to map things out so please go easy on me, sempai:

[Kindaichi Shounen no Jikenbo Returns](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=10442) [id=`10442`] should be mapped to [Season 2](https://www.thetvdb.com/?tab=season&seriesid=79460&seasonid=578651&lid=7) of [Young Kindaichi's Casebook](https://www.thetvdb.com/?tab=series&id=79460) [id=`79460`].

[Kindaichi Shounen no Jikenbo Returns (2015)](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=11367) [id=`11367`] should be mapped to [Season 3](https://www.thetvdb.com/?tab=season&seriesid=79460&seasonid=635235&lid=7) of [Young Kindaichi's Casebook](https://www.thetvdb.com/?tab=series&id=79460) [id=`79460`].

[Kindaichi Shounen no Jikenbo Returns (2015)](https://anidb.net/perl-bin/animedb.pl?show=anime&aid=11367) has a [special](https://anidb.net/perl-bin/animedb.pl?show=ep&eid=173572) that should be mapped to [Season 0 Episode 8](https://www.thetvdb.com/?tab=season&seriesid=79460&seasonid=26890&lid=7).

If I understand the mappings correctly, the above should translate to the following:

```xml
<anime anidbid="1240" tvdbid="79460" defaulttvdbseason="2" episodeoffset="" tmdbid="" imdbid="">
  <name>The Case File of Young Kindaichi Returns</name>
</anime>

<anime anidbid="11367" tvdbid="79460" defaulttvdbseason="3" episodeoffset="" tmdbid="" imdbid="">
  <name>Kindaichi Shounen no Jikenbo Returns (2015)</name>
  <mapping-list>
    <mapping anidbseason="0" tvdbseason="0">;1-8;</mapping>
  </mapping-list>
</anime>
```

Can someone verify this?

**Comment by sixtenbe** [comment]
anidbid 1240 isn't "The Case File of Young Kindaichi Returns", instead it's the 1997 series, so it appears you've managed to mix up ids in your suggested correction, but otherwise correct. So I've added them and checked the other related series so they should also be fixed.

If you have any other questions about mapping and such feel free to ask in this issue and such.
